import { AppState } from "@/types";

export const DEFAULT_APP_STATE: AppState = {
  version: "1.0.0",
  profile: {
    name: "",
    level: "intermediate",
    learningGoal: "Speak fluently without mentally translating from Hindi",
    dailyMinutes: 15,
    interests: ["College Life", "Job Interviews", "Technology", "Daily Routine"],
    preferredTopics: ["Daily Routine", "Explaining Projects", "Job Interviews"],
    speakingGoal: "Reduce hesitation and past tense errors",
    explanationLanguage: "hinglish",
    speechSpeed: "normal",
    hasCompletedOnboarding: false,
    createdAt: new Date().toISOString(),
  },
  progress: {
    speaking: 68,
    listening: 85,
    grammar: 62,
    vocabulary: 72,
    fluency: 64,
  },
  mistakes: [
    {
      id: "m-1",
      category: "grammar",
      topic: "Past Tense",
      original: "Yesterday I didn't went to college.",
      corrected: "Yesterday I didn't go to college.",
      explanation: "After 'did' or 'didn't', always use the base form of the verb ('go', not 'went').",
      count: 4,
      lastSeen: "Yesterday",
    },
    {
      id: "m-2",
      category: "sentence",
      topic: "Prepositions",
      original: "I am going college now.",
      corrected: "I am going to college now.",
      explanation: "Always use 'to' when indicating movement towards a destination.",
      count: 3,
      lastSeen: "2 days ago",
    },
    {
      id: "m-3",
      category: "vocabulary",
      topic: "Collocations",
      original: "I took breakfast at 8 AM.",
      corrected: "I had breakfast at 8 AM.",
      explanation: "In English, we say 'have breakfast' or 'eat breakfast' rather than 'take breakfast'.",
      count: 2,
      lastSeen: "3 days ago",
    },
  ],
  sessions: [
    {
      id: "s-1",
      date: "Today",
      durationMinutes: 15,
      activities: ["Listening", "Comprehension", "Speaking", "Correction"],
      completed: true,
      scores: { grammar: 75, fluency: 70, vocabulary: 80 },
      mistakesFound: ["m-1"],
    },
  ],
  phrases: [
    {
      id: "p-1",
      phrase: "I'm looking forward to it",
      meaning: "Excited and eager for a future event",
      example: "I am really looking forward to the hackathon demo.",
      category: "Conversational",
      practiced: true,
      savedAt: "2 days ago",
    },
    {
      id: "p-2",
      phrase: "Could you elaborate on that?",
      meaning: "Polite way to ask someone to explain more details",
      example: "Could you elaborate on how this AI model works?",
      category: "Professional",
      practiced: false,
      savedAt: "Yesterday",
    },
    {
      id: "p-3",
      phrase: "To be completely honest...",
      meaning: "Used to introduce an authentic, frank thought",
      example: "To be completely honest, I was nervous speaking at first.",
      category: "Casual",
      practiced: true,
      savedAt: "Today",
    },
  ],
  streak: 3,
  xp: 420,
  confidenceScore: 3, // 1 to 5 scale
  todayGoal: {
    targetMinutes: 15,
    completedMinutes: 8,
    targetActivities: 5,
    completedActivities: 2,
    focusArea: "Past Tense Mastery",
    completed: false,
  },
};
